### ISSUE TITLE
The initial parameter of DBN model

### ISSUE THREAD

**Issue by Ekkalak-T** [markovi/PyClick#10]
According to the [original paper](http://olivier.chapelle.cc/pub/DBN_www2009.pdf ) of DBN model, they wrote that DBN requires the input of a parameter γ.

Do we need to set this parameter? If yes, where can I find it?

My application is to predict the relevance of a document.

**Comment by markovi** [comment]
In PyClick, the parameter gamma is learned from click data, so you do not need to set it manually.

**Comment by Ekkalak-T** [comment]
@markovi Thank you very much for the answer. In the original paper when they used the predicted relevance from the au and su, they also used the confidence associated with these values.

The confidence is calculated by this formula. Could you please guide how to implement it with Pyclick?

![screen shot 2562-01-10 at 16 14 11](https://user-images.githubusercontent.com/22044205/50958311-fb2a3800-14f2-11e9-9c08-cea96adffe2c.png)

**Comment by markovi** [comment]
I am afraid I cannot help here as this seems to be beyond my understanding. :(
