### ISSUE TITLE
Problem About Parameter Estimation of UBM

### ISSUE THREAD

**Issue by jimmy-walker** [markovi/PyClick#11]
Thanks for sharing the code.

When I tested the UBM model, I encountered a question.
We all know that UBM uses the EM algorithm to estimate the parameter. For example, for a specific query q and item u, we calculate the attractiveness parameter Aqu.
Within the code, we will calculate the numerator and denominator of Aqu separately (An, Ad) and then combine to calculate Aqu = An/ Ad.
The problem is that if the first item u1 has only a few click behaviors, its attractiveness parameter may surpass the second item u2 who has many click behaviors.
For example :
the first item u1: An1=Ad1=100.
the second item u2: An2=9000, Ad2=10000
The result of Aqu1 will be bigger than Aqu2.

But I don't think it's normal. Cause the second item get more An.
Do you face the similar question during UBM model?
Looking forward to any reply. Thanks.

**Comment by markovi** [comment]
Dear Jimmy,

Thank you for the question. I think you are right, Aqu1 will be larger than Aqu2, even though it has fewer observations. However, this is an implicit drawback of UBM and of most other click models (e.g., DBN, CCM, etc). I think the solution would be to consider some kind of bayesian inference, where you not only estimate the attractiveness values Aqu, but also their distributions. You may want to have a look it this paper: https://zhangyuc.github.io/files/zhang10cikm.pdf. They do something of that kind.

Regards,
Ilya.
