### ISSUE TITLE
Memory issues of running PBM on large datasets

### ISSUE THREAD

**Issue by btg1998** [markovi/PyClick#12]
So, I was trying to run the PBM one on the entire Yandex Kaggle Train dataset[16 GB Size] by doing batchwise training, irrespective of the batch size chosen, the Model gets Killed when it is run on a 240 GB RAM Machine with 32 cores due to memory issues, any idea why this keeps happening. But Cascade Model runs without any memory issues on the entire dataset. The only significant difference between how they have been implemented is that, Cascade uses MLE for parameter estimation while PBM uses EM.

**Comment by markovi** [comment]
Unfortunately, this is a known issue with our implementation of EM parameter estimation. It loads all the model's parameters into RAM (and even copies them a few times). Because of this issue, we usually use smaller datasets (e.g., a few millions lines of input data).
