### ISSUE TITLE
Question about rank in _get_tail_clicks() of DBN

### ISSUE THREAD

**Issue by EloiseXu** [markovi/PyClick#13]
Hi, I'm confused when I see this in line 122, 123 and 124 in DBN.py:

            attr = session_params[rank][cls.param_names.attr].value()
            sat = session_params[rank][cls.param_names.sat].value()
            cont = session_params[rank][cls.param_names.cont].value()

why not "session_params[rank + start_rank][cls.param_names.attr].value()" ?

**Comment by markovi** [comment]
Dear Eloise,

What do you mean by start_rank? There is no such parameter in the code.

Just in case, in our implementation, all ranks start at 0.

Regards,
Ilya.

**Comment by EloiseXu** [comment]
Hi markovi,

  Here's the code:
  
  @classmethod
    def _get_tail_clicks(cls, search_session, start_rank, session_params):
        """
        Calculate P(C_r | C_{r-1}, ..., C_l, E_l = 1), P(E_r = 1 | C_{r-1}, ..., C_l, E_l = 1)
        for each r in [l, n) where l is start_rank.
        """
        exam = 1.0
        click_probs = []
        exam_probs = [exam]
        for rank, result in enumerate(search_session.web_results[start_rank:]):
            attr = session_params[rank][cls.param_names.attr].value()
            sat = session_params[rank][cls.param_names.sat].value()
            cont = session_params[rank][cls.param_names.cont].value()
            if result.click:
                click_prob = attr * exam
                exam = cont * (1 - sat)
            else:
                click_prob = 1 - attr * exam
                exam *= cont * (1 - attr) / click_prob
            click_probs.append(click_prob)
            exam_probs.append(exam)
        return click_probs, exam_probs

  I guess that the corresponding ranks of the three variables from session_params, attr, sat and cont, would be the same as that of the variable 'result' taken from search_session.web_results. Let's say the variable 'start_rank' equals 10. Then during the first iteration of the for loop the variable 'result.click' will be from the 11th candidate document in this session, while 'attr', 'sat' and 'cont' are from the 1st candidate since the variable 'rank' starts at 0, which is where I got confused. Did I get it correctly?

**Comment by markovi** [comment]
Alright, I see what you mean.

In general, you are right: if start_rank = 10, then the method should go over ranks 10, 11, 12, etc. This can be implemented in different ways. In your fist comment, you suggested one of the ways, which is using "rank + start_rank".

We implemented it differently in line 121:
"for rank, result in enumerate(search_session.web_results[start_rank:]):"
So our for-loop already begins with start_rank and goes till the end of web_results.

**Comment by EloiseXu** [comment]
Sorry, I still didn't get the point. How about this:
for rank, result in enumerate(search_session.web_results[start_rank:]):
attr = session_params[rank+start_rank][cls.param_names.attr].value()
sat = session_params[rank+start_rank][cls.param_names.sat].value()
cont = session_params[rank+start_rank][cls.param_names.cont].value()
if result.click:
click_prob = attr * exam
exam = cont * (1 - sat)
else:
click_prob = 1 - attr * exam
exam *= cont * (1 - attr) / click_prob

I did notice that search_session already starts from start_rank. However, session_params still starts from 0, causing result.click and attr, sat, cont from uncorresponding candidate document. Would you explain more about this? Thanks a lot.

**Comment by markovi** [comment]
Hmm, I think you are right and this might be a bug. Let's check with the author if this code. @varepsilon what do you think?

**Comment by varepsilon** [comment]
Yep, looks like a bug to me as well. Better use a simple range loop instead of enumerate here.

**Comment by EloiseXu** [comment]
Thanks a lot!

**Comment by EloiseXu** [comment]
thanks a lot!
