### ISSUE TITLE
Implementation of probit bayesian inference

### ISSUE THREAD

**Issue by rotc** [markovi/PyClick#14]
Hi, the book "Click models for Web search" notes that this project implemented the probit bayesian inference in "Learning Click Models via Probit Bayesian Inference", but I cannot find it. Could you tell me how to find the implementation? Thank you.

-- "The PyClick open source project, also written in Python, aims to provide an extendable implementation of existing click models and to simplify the development of new models. PyClick implements all basic click models discussed in Chapter 3. It mainly uses standard parameter estimation techniques described in Chapter 4, i.e., maximum likelihood estimation (MLE) and expectation-maximization (EM). In addition, it implements two alternative parameter estimation techniques, namely probit Bayesian inference (PBI) [Zhang et al., 2010] and the Bayesian browsing model (BBM) [Liu et al., 2009]."

**Comment by markovi** [comment]
Hello,

Thank you for the question and sorry for the delay in replying.

Probit and BBM were under development in the time of writing the book, but did not make it to the final version of PyClick, unfortunately. I still have some parts of that code and can share them if you like, but with no responsibility.

Regards,
Ilya.

**Comment by rotc** [comment]
> I still have some parts of that code and can share them if you like, but with no responsibility
I would really appreciate it if you could share them.

**Comment by rotc** [comment]
I would really appreciate it if you could share them.

**Comment by rotc** [comment]
> Hello,
> 
> Thank you for the question and sorry for the delay in replying.
> 
> Probit and BBM were under development in the time of writing the book, but did not make it to the final version of PyClick, unfortunately. I still have some parts of that code and can share them if you like, but with no responsibility.
> 
> Regards,
> Ilya.

I would really appreciate it if you could share them.

**Comment by markovi** [comment]
I attach the latest draft of the files. Please be aware that those might be neither complete nor working.

[Archive.zip](https://github.com/markovi/PyClick/files/4380264/Archive.zip)
