### ISSUE TITLE
The initial value for ParamEM

### ISSUE THREAD

**Issue by dlbrant** [markovi/PyClick#5]
Hi, there:

we are using PyClick for offline experiments now and find PyClick is amazing as its graceful architecture and implementation. Also we have learned a lot from the source code.

But there's one problem make us confused that the initial value for ParamEM (also ParamMLE) is self._numerator = 1
self._denominator = 2
which means its initial value will be 0.5.

And we also notice that in EMInference the code is like below, which means in every iteration, the new_click_model will deep copy from orig_click_model with param of 0.5.

So our questions are:
1. why you reset the model param in every iteration? is this an issue?
2. why the initial value is 1/2? is it theoretical or empirical?
3. why don't use the recommended initial value from UBM paper, in which init value of attr=0.2, exam=0.5?

#################################
````
    def infer_params(self, click_model, search_sessions):
        if search_sessions is None or len(search_sessions) == 0:
            return

        orig_click_model = copy.deepcopy(click_model)

        for iteration in xrange(self.iter_num):
            new_click_model = copy.deepcopy(orig_click_model)

            for search_session in search_sessions:
                current_session_params = click_model.get_session_params(search_session)
                new_session_params = new_click_model.get_session_params(search_session)

                for rank, result in enumerate(search_session.web_results):
                    for param_name, param in new_session_params[rank].items():
                        param.update(search_session, rank, current_session_params)

            click_model.params = new_click_model.params
````
####################################

**Comment by dlbrant** [comment]
one of my partner notice that if we don't copy from the orig_click_model in every iteration, then the click model will not convergence in test data.

so reset the param to 1/2 in every iteration is somehow like regularization?

**Comment by varepsilon** [comment]
Hi,

Thanks for the comments.

1. If you look at the formulas for the parameter updates for EM-models, they are not really _updates_. In each case we populate parameters from scratch by computing some kind of sum and dividing it by the number of sessions. So starting from `orig_click_model` indeed works as regularization.
2. Why 1/2? As long as you have enough iterations, the initial value should not matter much. We put 1/2 as the most basic thing you can come up with.
3. Yes, you may gain by setting it differently for different parameters for some models. We just left it simple uniformly for all models.

Feel free to reopen the issue if you still have comments.

**Comment by dlbrant** [comment]
Thanks for the reply :)

Still I have some more questions:

1.How can we suppress the impact of initial value? Or shall we remove the low frequency qu-pair? What is your suggestion for the threshold of query or qu-pair frequency?

2.Another question is how do you use the click model parameters? I mean how do you remove the noise in the params as there are some noise from user clicks especially for the low frequency query sessions?

**Comment by varepsilon** [comment]
These are both good questions and I don't have a suggestion for you. Depending on the application you may want to avoid filtering at all, or, e.g.,

>  discard any query for which we have less than 10 sessions, and we discard all query-document tuples for which we have less than 10 observations

as done by Dupret et al. in their original 2008 UBM paper.

**Comment by dlbrant** [comment]
Thanks for that!

I will try out the 10 session threshold in our experiments.
