### ISSUE TITLE
Applicability outside websearch

### ISSUE THREAD

**Issue by EikeDehling** [markovi/PyClick#7]
We're using and evaluating these click models currently, on data from our search system. Our system is a bit different from web search - it's searching in databases of CVs(Job applicants) and Vacancies(Jobs).

What we're seeing is that our dataset is much smaller than web search datasets - we have around 60.000 search sessions over 2017-Q4. Another thing that we observe is many unique queries and few queries that are performed multiple times.

Our end goal is using the relevance predictions as input for learning to rank.

Could you give your intuition / insights on some questions?

- Are queries that are executed multiple times needed for good relevance predictions - or would unique queries also be fine? My feeling here
- What queries to include? So far, we've filtered out queries with only one click. We're considering also filtering out queries were the user later edited/changed the query - intuition is that if they changed the query, the initial results were probably not that good?
- How would you use the predictions from these models in Learning to Rank.  As an input feature or as the "ground truth"?  We were hoping to avoid large-scale human assessments, and rather use predictions from these models...

Would be gratefull if you could share your ideas!

**Comment by varepsilon** [comment]
- There are multiple things you can try when you have too many unique queries. The simplest would probably be conflating multiple queries into one, e.g., by selecting only important words. Another option is to have a hybrid setup where your examination probability depends on rank (like in PBM, or more complex UBM), but your attractiveness probability is obtained from a classifier, such as logistic regression or neural network (simplest neural network would just use dot-product of embeddings; see also http://nn4ir.com/). This is, unfortunately, not implemented in PyClick (yet?), but there is a similar model used in [one of my papers](https://github.com/varepsilon/cas-eval). 
- I wouldn't remove "bad" queries as they provide useful negative signal
- If you want to avoid human assessment, you have no choice as to use _something_ as ground truth. Click models could be one example, namely attractiveness params, satisfaction params or products thereof.

Hope that helps.

**Comment by EikeDehling** [comment]
Thanks for the input!
