### ISSUE TITLE
Question about QueryID column in input data format

### ISSUE THREAD

**Issue by Ekkalak-T** [markovi/PyClick#8]
I am preparing search log to have the same format as YandexRelPredChallenge.

But I am confused about how to generate QueryID column. 

- Can we just use the search_id? 

- Otherwise, should we group searches having the same query/keyword to have the same QueryID? 
For example, all searches with keyword "coffee" must have the same QueryID. 
- Can we still group the searches if multiple searches with the same query/keyword having different results and order?

**Comment by varepsilon** [comment]
Thanks for the question. Originally, whenever the text of the query is the same, `QueryID`s should also be the same, even when the results or their order is different. That's where I would start.

Then, if you think that the model does not manage to generalize well enough, you can try some other tricks, like grouping similar queries to the same `QueryID` or going more fancy with matrix factorization (see, e.g., paper titled "Personalized Click Model through Collaborative Filtering").

**Comment by Ekkalak-T** [comment]
Thank you for the answer 👍
